apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    # case-sensitive
    eventing.knative.dev/broker.class: Kafka
  name: br
  namespace: sandbox
spec:
  # Configuration specific to this broker.
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
    namespace: knative-eventing

---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: tr
  namespace: sandbox
spec:
  broker: br
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
---
apiVersion: v1
kind: Service
metadata:
  name: event-display
  namespace: sandbox
spec:
  selector:
    app: event-display
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  namespace: sandbox
  labels:
    app: event-display
spec:
  containers:
  - name: event-display
    image: quay.io/pierdipi/event_display-a5130e9507c3d4c9b58499a4ac90be69
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
