apiVersion: operator.serverless.openshift.io/v1alpha1
kind: KnativeKafka
metadata:
  name: knative-kafka
  namespace: knative-eventing
spec:
  channel:
    enabled: false
    bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092
  source:
    enabled: true
  sink:
    enabled: false
  broker:
    enabled: true
    defaultConfig:
      bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092
      numPartitions: 10
      replicationFactor: 3
