apiVersion: v1
kind: Pod
metadata:
  labels:
    run: curl
  annotations:
    sidecar.istio.io/inject: "true"
  name: curl
  namespace: sandbox
spec:
  containers:
    - args:
        - -X
        - POST
        - -v
        - -H
        - 'content-type: application/json'
        - -H
        - 'ce-specversion: 1.0'
        - -H
        - 'ce-source: my/curl/command'
        - -H
        - 'ce-type: my.demo.event'
        - -H
        - 'ce-id: 0815'
        - -d
        - '{"name":"Bob2"}'
        - https://kafka-broker-ingress.knative-eventing.svc.cluster.local/sandbox/br
      image: docker.io/curlimages/curl
      name: curl
      resources: { }
  dnsPolicy: ClusterFirst
  restartPolicy: Never
